name: Build & Upload Debug APK

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Java 설정 (Gradle 빌드를 위한 환경)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3. Gradle Debug APK 빌드
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 4. 릴리즈 자산 업로드
      - name: Upload Debug APK to Release
        uses: actions/upload-release-asset@v3
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
